<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AnnouncementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUserId = DB::table('users')->where('user_type', 'administrator')->first()?->userID ?? 1;

        $announcements = [
            // Parents
            [
                'title' => 'Parent-Teacher Conference Schedule',
                'content' => 'The annual parent-teacher conference will be held on March 15-17, 2024. Please schedule your appointments through the school portal.',
                'category' => 'important',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(2),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'title' => 'School Fees Payment Reminder',
                'content' => 'Gentle reminder to settle outstanding school fees by the end of this month. Payment options are available at the school office.',
                'category' => 'notice',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(5),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'title' => 'School Field Trip Permission',
                'content' => 'Students will be going on a field trip to the National Museum next week. Please sign the permission slip sent through your child.',
                'category' => 'event',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(7),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'title' => 'Annual Family Day Celebration',
                'content' => 'Join us for our Annual Family Day on April 5, 2024! There will be fun activities, games, and delicious food for the whole family.',
                'category' => 'event',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(10),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now()->subDays(10),
            ],
            [
                'title' => 'Updated Class Schedules',
                'content' => 'Due to recent adjustments, class schedules for Grade 4-6 have been updated. Please check the parent portal for the latest schedules.',
                'category' => 'update',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(12),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => Carbon::now()->subDays(12),
            ],
            // Teachers
            [
                'title' => 'Faculty Meeting - Curriculum Review',
                'content' => 'All teachers are required to attend the faculty meeting on March 20 to discuss the new curriculum updates and implementation strategies.',
                'category' => 'important',
                'audience' => 'teachers',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(3),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'title' => 'Professional Development Workshop',
                'content' => 'A workshop on modern teaching methodologies will be held on March 25. Registration is now open through the staff portal.',
                'category' => 'event',
                'audience' => 'teachers',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(6),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(6),
                'updated_at' => Carbon::now()->subDays(6),
            ],
            [
                'title' => 'Grade Submission Deadline',
                'content' => 'Please submit all third quarter grades by March 30. Late submissions will require written justification.',
                'category' => 'notice',
                'audience' => 'teachers',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(8),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now()->subDays(8),
            ],
            [
                'title' => 'New Learning Management System',
                'content' => 'The school will implement a new LMS starting next semester. Training sessions will be scheduled for all teaching staff.',
                'category' => 'update',
                'audience' => 'teachers',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(11),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(11),
                'updated_at' => Carbon::now()->subDays(11),
            ],
            [
                'title' => 'Classroom Supplies Request Form',
                'content' => 'Teachers can now submit requests for additional classroom supplies through the new online form. Deadline is April 5.',
                'category' => 'notice',
                'audience' => 'teachers',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(13),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(13),
                'updated_at' => Carbon::now()->subDays(13),
            ],
            // Principal
            [
                'title' => 'Board Meeting Summary',
                'content' => 'The board has approved the budget for the new school year. Key allocations include facility improvements and new equipment purchases.',
                'category' => 'important',
                'audience' => 'principal',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(4),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            [
                'title' => 'District Superintendent Visit',
                'content' => 'The district superintendent will be visiting our school on April 10 for an inspection and evaluation.',
                'category' => 'important',
                'audience' => 'principal',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(9),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(9),
                'updated_at' => Carbon::now()->subDays(9),
            ],
            [
                'title' => 'Annual School Performance Report',
                'content' => 'The annual performance report is due to the district office by March 28. Please ensure all data is accurate and complete.',
                'category' => 'notice',
                'audience' => 'principal',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(14),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(14),
                'updated_at' => Carbon::now()->subDays(14),
            ],
            // Everyone
            [
                'title' => 'School Closure Notice',
                'content' => 'The school will be closed on March 8, 2024 due to scheduled maintenance. Classes will resume on March 11, 2024.',
                'category' => 'notice',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subWeek(),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subWeek(),
                'updated_at' => Carbon::now()->subWeek(),
            ],
            [
                'title' => 'Fire Drill Schedule',
                'content' => 'A fire drill will be conducted on March 22 at 10:00 AM. Please follow safety procedures and evacuation routes.',
                'category' => 'important',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(15),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => Carbon::now()->subDays(15),
            ],
            [
                'title' => 'School Intramurals 2024',
                'content' => 'The annual school intramurals will be held from April 15-19. All students, teachers, and staff are encouraged to participate.',
                'category' => 'event',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subWeeks(2),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subWeeks(2),
                'updated_at' => Carbon::now()->subWeeks(2),
            ],
            [
                'title' => 'New Security Measures',
                'content' => 'Enhanced security measures will be implemented starting next month, including visitor registration and ID scanning.',
                'category' => 'update',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subWeeks(3),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subWeeks(3),
                'updated_at' => Carbon::now()->subWeeks(3),
            ],
            [
                'title' => 'Library Hours Extended',
                'content' => 'The school library will now be open until 6:00 PM on weekdays to better serve students and staff.',
                'category' => 'update',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subWeeks(4),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subWeeks(4),
                'updated_at' => Carbon::now()->subWeeks(4),
            ],
            // Faculty (teachers + principal + administrator)
            [
                'title' => 'Staff Development Day',
                'content' => 'All faculty members are required to attend the staff development day on April 3. Topics include student welfare and academic excellence.',
                'category' => 'important',
                'audience' => 'faculty',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(16),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(16),
                'updated_at' => Carbon::now()->subDays(16),
            ],
            [
                'title' => 'End-of-Year Evaluation Process',
                'content' => 'The evaluation process for all faculty members will begin on April 20. Please prepare necessary documentation.',
                'category' => 'notice',
                'audience' => 'faculty',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(17),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(17),
                'updated_at' => Carbon::now()->subDays(17),
            ],
            // Additional variety
            [
                'title' => 'Health and Wellness Program',
                'content' => 'Join our new health and wellness program for parents! Monthly workshops on nutrition, fitness, and mental health.',
                'category' => 'event',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(18),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(18),
                'updated_at' => Carbon::now()->subDays(18),
            ],
            [
                'title' => 'Science Fair Winners Announcement',
                'content' => 'Congratulations to all participants! Winners will be announced on March 29 during the school assembly.',
                'category' => 'event',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(19),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(19),
                'updated_at' => Carbon::now()->subDays(19),
            ],
            [
                'title' => 'Technology Integration Training',
                'content' => 'Teachers are invited to attend technology integration training focusing on digital learning tools and platforms.',
                'category' => 'event',
                'audience' => 'teachers',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(20),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'title' => 'School Anniversary Celebration',
                'content' => 'Mark your calendars! Our school\'s founding anniversary will be celebrated on May 15 with special activities and programs.',
                'category' => 'event',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(21),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(21),
                'updated_at' => Carbon::now()->subDays(21),
            ],
            [
                'title' => 'Student Progress Reports',
                'content' => 'Progress reports for the third quarter are now available. Parents can access them through the parent portal.',
                'category' => 'update',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(22),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(22),
                'updated_at' => Carbon::now()->subDays(22),
            ],
            [
                'title' => 'Emergency Contact Update Required',
                'content' => 'All parents are requested to update emergency contact information through the school portal by March 31.',
                'category' => 'notice',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(23),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(23),
                'updated_at' => Carbon::now()->subDays(23),
            ],
            [
                'title' => 'Cafeteria Menu Changes',
                'content' => 'The cafeteria will be introducing healthier meal options starting April 1. New menus are posted on the bulletin board.',
                'category' => 'update',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(24),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(24),
                'updated_at' => Carbon::now()->subDays(24),
            ],
            [
                'title' => 'Anti-Bullying Campaign Launch',
                'content' => 'We are launching a school-wide anti-bullying campaign. Parents, teachers, and students are encouraged to participate.',
                'category' => 'important',
                'audience' => 'everyone',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(25),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(25),
                'updated_at' => Carbon::now()->subDays(25),
            ],
            [
                'title' => 'PTA General Assembly',
                'content' => 'The quarterly PTA general assembly will be held on April 8 at 2:00 PM in the school auditorium. All parents are welcome.',
                'category' => 'event',
                'audience' => 'parents',
                'created_by' => $adminUserId,
                'published_at' => Carbon::now()->subDays(26),
                'expires_at' => null,
                'is_active' => true,
                'created_at' => Carbon::now()->subDays(26),
                'updated_at' => Carbon::now()->subDays(26),
            ],
        ];

        DB::table('announcements')->insert($announcements);
    }
}
