<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUserId = DB::table('users')->where('user_type', 'administrator')->first()?->userID ?? 1;

        $schedules = [
            // Recent/Past Schedules
            [
                'title' => 'Parent–Teacher Conference',
                'description' => 'Scheduled for March 15–17, 2024. Please confirm your attendance.',
                'scheduled_date' => Carbon::now()->subHours(2),
                'start_time' => null,
                'end_time' => null,
                'category' => 'meeting',
                'priority' => 'high',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => true,
                'created_at' => Carbon::now()->subHours(2),
                'updated_at' => Carbon::now()->subHours(2),
            ],
            [
                'title' => 'Science Fair Winners',
                'description' => 'Congratulations to all participants in the annual science fair.',
                'scheduled_date' => Carbon::now()->subDay(),
                'start_time' => null,
                'end_time' => null,
                'category' => 'event',
                'priority' => 'medium',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => true,
                'created_at' => Carbon::now()->subDay(),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'title' => 'School Maintenance',
                'description' => 'Building maintenance scheduled for this weekend.',
                'scheduled_date' => Carbon::now()->subDays(3),
                'start_time' => null,
                'end_time' => null,
                'category' => 'maintenance',
                'priority' => 'low',
                'visibility' => 'administrator',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => true,
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],

            // Upcoming Schedules for Parents
            [
                'title' => 'PTA General Assembly',
                'description' => 'Quarterly PTA meeting to discuss school projects and fundraising activities.',
                'scheduled_date' => Carbon::now()->addDays(3),
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'category' => 'meeting',
                'priority' => 'high',
                'visibility' => 'parents',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Annual Family Day',
                'description' => 'Fun activities, games, and food for the whole family. Don\'t miss it!',
                'scheduled_date' => Carbon::now()->addDays(7),
                'start_time' => '08:00:00',
                'end_time' => '17:00:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'parents',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Parent Orientation: New LMS',
                'description' => 'Learn how to use the new learning management system to track your child\'s progress.',
                'scheduled_date' => Carbon::now()->addDays(10),
                'start_time' => '15:00:00',
                'end_time' => '16:30:00',
                'category' => 'event',
                'priority' => 'medium',
                'visibility' => 'parents',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Field Trip Permission Deadline',
                'description' => 'Last day to submit permission slips for the National Museum field trip.',
                'scheduled_date' => Carbon::now()->addDays(12),
                'start_time' => null,
                'end_time' => null,
                'category' => 'other',
                'priority' => 'high',
                'visibility' => 'parents',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Parent Consultation Day',
                'description' => 'Individual consultations with teachers available. Book your slot through the portal.',
                'scheduled_date' => Carbon::now()->addDays(18),
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'category' => 'meeting',
                'priority' => 'medium',
                'visibility' => 'parents',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Upcoming Schedules for Teachers
            [
                'title' => 'Faculty Meeting - Curriculum Review',
                'description' => 'Discuss new curriculum updates and implementation strategies.',
                'scheduled_date' => Carbon::now()->addDays(5),
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'category' => 'meeting',
                'priority' => 'high',
                'visibility' => 'teachers',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Professional Development Workshop',
                'description' => 'Workshop on modern teaching methodologies and classroom management.',
                'scheduled_date' => Carbon::now()->addDays(8),
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'teachers',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Grade Submission Deadline',
                'description' => 'All third quarter grades must be submitted by end of day.',
                'scheduled_date' => Carbon::now()->addDays(14),
                'start_time' => null,
                'end_time' => null,
                'category' => 'other',
                'priority' => 'high',
                'visibility' => 'teachers',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Technology Integration Training',
                'description' => 'Learn to use digital learning tools and platforms in your classroom.',
                'scheduled_date' => Carbon::now()->addDays(16),
                'start_time' => '13:00:00',
                'end_time' => '16:00:00',
                'category' => 'event',
                'priority' => 'medium',
                'visibility' => 'teachers',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Classroom Supplies Distribution',
                'description' => 'Pick up your approved classroom supplies from the supply room.',
                'scheduled_date' => Carbon::now()->addDays(20),
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'category' => 'event',
                'priority' => 'low',
                'visibility' => 'teachers',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Upcoming Schedules for Principal
            [
                'title' => 'Board Meeting',
                'description' => 'Monthly board meeting to discuss school budget and performance.',
                'scheduled_date' => Carbon::now()->addDays(6),
                'start_time' => '10:00:00',
                'end_time' => '12:00:00',
                'category' => 'meeting',
                'priority' => 'high',
                'visibility' => 'principal',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'District Superintendent Visit',
                'description' => 'Prepare for the district superintendent\'s inspection and evaluation.',
                'scheduled_date' => Carbon::now()->addDays(13),
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'category' => 'review',
                'priority' => 'high',
                'visibility' => 'principal',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Annual Performance Report Deadline',
                'description' => 'Submit comprehensive annual performance report to district office.',
                'scheduled_date' => Carbon::now()->addDays(17),
                'start_time' => null,
                'end_time' => null,
                'category' => 'other',
                'priority' => 'high',
                'visibility' => 'principal',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Upcoming Schedules for Administrator
            [
                'title' => 'PTA Coordination Meeting',
                'description' => 'Finalize school fundraising and improvement plans.',
                'scheduled_date' => Carbon::now()->addDays(5),
                'start_time' => '09:00:00',
                'end_time' => '10:00:00',
                'category' => 'meeting',
                'priority' => 'high',
                'visibility' => 'administrator',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Quarterly Academic Review',
                'description' => 'Evaluate student performance and upcoming exam preparations.',
                'scheduled_date' => Carbon::now()->addDays(10),
                'start_time' => '13:30:00',
                'end_time' => '14:00:00',
                'category' => 'academic',
                'priority' => 'medium',
                'visibility' => 'administrator',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'School Safety Audit',
                'description' => 'Inspect facilities to ensure a safe learning environment.',
                'scheduled_date' => Carbon::now()->addDays(15),
                'start_time' => '10:00:00',
                'end_time' => '11:00:00',
                'category' => 'review',
                'priority' => 'low',
                'visibility' => 'administrator',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Upcoming Schedules for Everyone
            [
                'title' => 'Fire Drill',
                'description' => 'School-wide fire drill. Please follow safety procedures and evacuation routes.',
                'scheduled_date' => Carbon::now()->addDays(4),
                'start_time' => '10:00:00',
                'end_time' => '10:30:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'School Intramurals 2024',
                'description' => 'Annual sports competition. All students, teachers, and staff are encouraged to participate.',
                'scheduled_date' => Carbon::now()->addDays(9),
                'start_time' => '08:00:00',
                'end_time' => '17:00:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'School Foundation Day',
                'description' => 'Celebrate our school\'s anniversary with special programs and activities.',
                'scheduled_date' => Carbon::now()->addDays(25),
                'start_time' => '08:00:00',
                'end_time' => '16:00:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Health and Safety Seminar',
                'description' => 'Important seminar on health protocols and safety measures.',
                'scheduled_date' => Carbon::now()->addDays(11),
                'start_time' => '14:00:00',
                'end_time' => '16:00:00',
                'category' => 'event',
                'priority' => 'medium',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Faculty schedules (principal + teachers + administrator)
            [
                'title' => 'Staff Development Day',
                'description' => 'All faculty members required to attend. Topics: student welfare and academic excellence.',
                'scheduled_date' => Carbon::now()->addDays(19),
                'start_time' => '08:00:00',
                'end_time' => '16:00:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'faculty',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'End-of-Year Evaluation Process',
                'description' => 'Faculty performance evaluations begin. Please prepare necessary documentation.',
                'scheduled_date' => Carbon::now()->addDays(22),
                'start_time' => null,
                'end_time' => null,
                'category' => 'review',
                'priority' => 'high',
                'visibility' => 'faculty',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Additional varied schedules
            [
                'title' => 'Science Fair Opening',
                'description' => 'Opening ceremony for the annual science fair. Parents and students welcome.',
                'scheduled_date' => Carbon::now()->addDays(21),
                'start_time' => '09:00:00',
                'end_time' => '11:00:00',
                'category' => 'event',
                'priority' => 'medium',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Art Exhibition Setup',
                'description' => 'Help needed for setting up the student art exhibition in the main hall.',
                'scheduled_date' => Carbon::now()->addDays(23),
                'start_time' => '13:00:00',
                'end_time' => '17:00:00',
                'category' => 'event',
                'priority' => 'low',
                'visibility' => 'teachers',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Vaccine Clinic for Students',
                'description' => 'Free vaccination for all students. Consent forms required from parents.',
                'scheduled_date' => Carbon::now()->addDays(24),
                'start_time' => '08:00:00',
                'end_time' => '12:00:00',
                'category' => 'event',
                'priority' => 'high',
                'visibility' => 'everyone',
                'created_by' => $adminUserId,
                'is_active' => true,
                'is_completed' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('schedules')->insert($schedules);
    }
}
